export const LAYER = {
  ADD: 'LAYER_ADD',
  REMOVE: 'LAYER_REMOVE'
};

export const MAP = {
  GET_CONFIG: 'MAP_GET_CONFIG',
  SET_VIEW: 'MAP_SET_VIEW',
  SET_CENTER: 'MAP_SET_CENTER',
  SET_EXTENT: 'MAP_SET_EXTENT',
  SET_ZOOM: 'MAP_SET_ZOOM',
  ZOOM_IN: 'MAP_ZOOM_IN',
  ZOOM_OUT: 'MAP_ZOOM_OUT'
};
